[package]
org = "ballerina"
name = "oauth2"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../oauth2-native/build/libs/oauth2-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "oauth2"
version = "@project.version@"
