[package]
org = "ballerina"
name = "oauth2"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "cache"
version = "@stdlib.cache.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[platform.java11.dependency]]
path = "../oauth2-native/build/libs/oauth2-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "oauth2"
version = "@project.version@"
