[package]
org = "ballerina"
name = "oauth2"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["security", "authorization", "introspection"]
repository = "https://github.com/ballerina-platform/module-ballerina-oauth2"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/oauth2-native-@project.version@.jar"
