[package]
org = "ballerina"
name = "oauth2"
version = "2.1.0"
authors = ["Ballerina"]
keywords = ["security", "authorization", "introspection"]
repository = "https://github.com/ballerina-platform/module-ballerina-oauth2"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/oauth2-native-2.1.0-SNAPSHOT.jar"
