[package]
org = "ballerina"
name = "oauth2"
version = "2.3.1"
authors = ["Ballerina"]
keywords = ["security", "authorization", "introspection"]
repository = "https://github.com/ballerina-platform/module-ballerina-oauth2"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/oauth2-native-2.3.1-SNAPSHOT.jar"
